- name: &fqdn 2016.changelog.com
  hosts: 2016
  gather_facts: true

  vars:
    host: "{{ inventory_hostname }}"
    hostname: "{{ ansible_ssh_host }}"
    docker_dev: /dev/sdc

  roles:
    - role: base
      tags: [base]

    - role: docker
      tags: [docker]

    - role: nginx
      tags: [nginx]

    - role: check
      tags: [check]
      https: true
      force_https: true
      https_common_name: "*.changelog.com"

    - role: postgres
      tags: [postgres]

- name: dotcom
  hosts: app
  gather_facts: false

  vars:
    changelog_app_repository: git@github.com:thechangelog/dotcom.git

  roles:
  - role: changelog
    tags: [changelog]
