- name: &fqdn 2016.changelog.com
  hosts: 2016
  gather_facts: true

  vars:
    host: "{{ inventory_hostname }}"
    hostname: "{{ ansible_ssh_host }}"
    docker_dev: /dev/sdc
    web_volume_path: /data/www
    papertrail_log_destination: tcp+tls://logs4.papertrailapp.com:35714
    changelog_https_cert: "{{ lookup('env', 'HTTPS_CERT') }}"
    changelog_https_key: "{{ lookup('env', 'HTTPS_KEY') }}"
    changelog_https_chain: "{{ lookup('env', 'HTTPS_CHAIN') }}"
    authorized_keys: "{{ lookup('env', 'AUTHORIZED_KEYS') }}"
    postgres_admin_pass: "{{ lookup('env', 'PG_ADMIN_PASS') }}"

  roles:
    - role: base
      tags: [base]

    - role: docker
      tags: [docker]

    - role: nginx
      tags: [nginx]

    - role: changelog
      tags: [changelog]

    - role: check
      tags: [check]
      https: true
      force_https: true
      https_common_name: "*.changelog.com"

    - role: postgres
      tags: [postgres]
