- name: &fqdn 2016.changelog.com
  hosts: 2016
  gather_facts: true

  vars:
    host: "{{ inventory_hostname }}"
    hostname: "{{ ansible_ssh_host }}"
    docker_dev: /dev/sdc
    web_volume_path: /data/www
    papertrail_log_destination: tcp+tls://logs4.papertrailapp.com:35714

  roles:
    - role: base
      tags: [base]

    - role: docker
      tags: [docker]

    - role: nginx
      tags: [nginx]
