- name: &fqdn 2016.changelog.com
  hosts: 2016
  gather_facts: true

  vars:
    host: "{{ inventory_hostname }}"
    hostname: "{{ ansible_ssh_host }}"
    docker_dev: /dev/sdc

  roles:
    - role: base
      tags: [base]

    - role: docker
      tags: [docker]

    - role: nginx
      tags: [nginx]

    - role: postgres
      tags: [postgres]

- name: dotcom
  hosts: app
  gather_facts: false

  vars:
    changelog_app_repository: git@github.com:thechangelog/dotcom.git

  roles:
  - role: changelog
    tags: [changelog]

  - role: check
    tags: [check, https]
    https: true
    force_https: true
    https_common_name: "*.changelog.com"
    response_server: Cowboy

  - role: check
    tags: [check, https]
    https: true
    https_common_name: "*.changelog.com"
    path: "/wp-content/uploads/blinksale-image.jpg"
    response_server: nginx
