- name: &fqdn 2016.changelog.com
  hosts: 2016
  gather_facts: true

  vars:
    host: "{{ inventory_hostname }}"
    hostname: "{{ ansible_ssh_host }}"
    docker_dev: /dev/sdc

  roles:
    - role: base
      tags: [base]

    - role: docker
      tags: [docker]

    - role: nginx
      tags: [nginx]

    - role: postgres
      tags: [postgres]

    - role: changelog
      tags: [changelog]

- name: dotcom
  hosts: app
  gather_facts: false

  roles:
  - role: dotcom
    tags: [dotcom]

  - role: check
    tags: [check, https]
    https: true
    force_https: true
    https_common_name: "*.changelog.com"
    response_server: Cowboy

  - role: check
    tags: [check, legacy, uploads]
    https: true
    https_common_name: "*.changelog.com"
    path: "/wp-content/uploads/blinksale-image.jpg"

  - role: check
    tags: [check, legacy, posts]
    https: true
    https_common_name: "*.changelog.com"
    path: "/reducing-server-anxiety"
    http_checks:
      - "'Host: {{ fqdn }}' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://{{ fqdn }}/posts/reducing-server-anxiety' in http_response.stderr"

  - role: check
    tags: [check, static]
    https: true
    https_common_name: "*.changelog.com"
    path: "/css/app.css"

  - role: check
    tags: [check, uploads]
    https: true
    https_common_name: "*.changelog.com"
    path: "/uploads/avatars/V1/avatar_small.png"

  - role: check
    tags: [check, changelogfm]
    fqdn: changelog.fm
    path: "/1"
    http_checks:
      - "'Host: changelog.fm' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://2016.changelog.com/podcast/1' in http_response.stderr"

- name: concourse
  hosts: ci
  gather_facts: true

  roles:
    - role: concourse
      tags: [concourse]

    - role: check
      tags: [check]
      https: true
      https_common_name: "*.changelog.com"
      response_status: HTTP/1.1 302 Found
