- name: Changelog 2016 - CI
  hosts: ci
  gather_facts: true

  roles:
    - role: concourse
      tags: [concourse]

    - role: check
      tags: [check]
      https: true
      https_common_name: "*.changelog.com"
      response_body: "no pipelines configured"
