- name: Changelog
  hosts: c16
  gather_facts: true

  vars:
    host: "{{ inventory_hostname }}"
    hostname: "{{ ansible_ssh_host }}"
    docker_dev: /dev/sdc

  roles:
    - role: base
      tags: [base]

    - role: docker
      tags: [docker]

    - role: nginx
      tags: [nginx]

    - role: postgres
      tags: [postgres]

    - role: changelog
      tags: [changelog]
