- name: Changelog App
  hosts: app
  gather_facts: false

  roles:
  - role: dotcom
    tags: [dotcom]

  - role: check
    tags: [check, https]
    https: true
    force_https: true
    https_common_name: "*.changelog.com"
    response_server: Cowboy

  - role: check
    tags: [check, http]
    http_checks:
      - "'Host: {{ fqdn }}' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://{{ fqdn }}/' in http_response.stderr"

  - role: check
    tags: [check, legacy, uploads]
    https: true
    https_common_name: "*.changelog.com"
    path: "/wp-content/uploads/blinksale-image.jpg"

  - role: check
    tags: [check, legacy, posts]
    https: true
    https_common_name: "*.changelog.com"
    path: "/reducing-server-anxiety"
    http_checks:
      - "'Host: {{ fqdn }}' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://{{ fqdn }}/posts/reducing-server-anxiety' in http_response.stderr"

  - role: check
    tags: [check, legacy, podcasts]
    https: true
    https_common_name: "*.changelog.com"
    path: "/201"
    http_checks:
      - "'Host: {{ fqdn }}' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://{{ fqdn }}/podcast/201' in http_response.stderr"

  - role: check
    tags: [check, legacy, podcasts]
    https: true
    https_common_name: "*.changelog.com"
    path: "/gotime-14"
    http_checks:
      - "'Host: {{ fqdn }}' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://{{ fqdn }}/gotime/14' in http_response.stderr"

  - role: check
    tags: [check, legacy, podcasts]
    https: true
    https_common_name: "*.changelog.com"
    path: "/rfc-7"
    http_checks:
      - "'Host: {{ fqdn }}' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://{{ fqdn }}/rfc/7' in http_response.stderr"

  - role: check
    tags: [check, static]
    https: true
    https_common_name: "*.changelog.com"
    path: "/css/app.css"

  - role: check
    tags: [check, uploads]
    https: true
    https_common_name: "*.changelog.com"
    path: "/uploads/avatars/V1/avatar_small.png"

  - role: check
    tags: [check, changelogfm]
    fqdn: changelog.fm
    path: "/1"
    http_checks:
      - "'Host: changelog.fm' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://changelog.com/podcast/1' in http_response.stderr"

  - role: check
    tags: [check, gotimefm]
    fqdn: gotime.fm
    path: "/10"
    http_checks:
      - "'Host: gotime.fm' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://changelog.com/gotime/10' in http_response.stderr"

  - role: check
    tags: [check, rfcfm]
    fqdn: rfc.fm
    path: "/4"
    http_checks:
      - "'Host: rfc.fm' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://changelog.com/rfc/4' in http_response.stderr"
