- name: &fqdn netdata.changelog.com
  hosts: app
  gather_facts: false

  vars:
    fqdn: *fqdn

  roles:
  - role: netdata
    tags: [netdata]

  - role: check
    tags: [check, https]
    https: true
    https_common_name: "*.changelog.com"

  - role: check
    tags: [check, http]
    http_checks:
      - "'Host: {{ fqdn }}' in http_response.stderr"
      - "'HTTP/1.1 301 Moved Permanently' in http_response.stderr"
      - "'Location: https://{{ fqdn }}/' in http_response.stderr"
