# authorized_keys: required, ensure it is defined securely
packages:
  - binutils
  - curl
  - dstat
  - ethtool
  - git
  - htop
  - jq
  - iptraf
  - jnettop
  - language-pack-en
  - lvm2
  - ntp
  - sudo
  - sysstat
  - tmux
  - tree
  - vim
  - vnstat
