# changelog_https_cert: required, ensure it is defined securely
# changelog_https_key: required, ensure it is defined securely
# changelog_https_chain: required, ensure it is defined securely
changelog_max_upload_size_mb: 60
