https: false
force_https: false
https_common_name: "{{ fqdn }}"
untrusted_ca: false
path: "/"
check_basic_auth: false

response_status: HTTP/1.1 200 OK
response_server: nginx
response_body: ""

http_checks:
  - "'Host: {{ fqdn }}' in http_response.stderr"
  - "response_status in http_response.stderr"
  - "response_server in http_response.stderr"
  - "response_body in http_response.stdout"

https_checks:
  - "'CN={{ https_common_name }}' in http_response.stderr"
