- name: checkout app
  register: app_version
  git:
    accept_hostkey: yes
    dest: "{{ web_volume_path }}/dotcom"
    force: yes
    update: yes
    repo: "{{ changelog_app_repository }}"

- name: ensure app is running
  when: app_version | changed
  shell: >
    docker run --detach --tty
    --restart unless-stopped
    --label fqdn={{ fqdn }}
    --name dotcom.{{ lookup('pipe','date +%Y%m%d.%H%M%S') }}
    --net {{ nginx_net }}
    --net-alias dotcom
    --volume {{ web_volume_path }}/dotcom:/app:rw
    --workdir /app
    --log-driver syslog --log-opt tag=dotcom.{{ lookup('pipe','date +%Y%m%d.%H%M%S') }} --log-opt syslog-address={{ papertrail_log_destination }}
    --env MIX_ENV=prod
    --env PORT=4000
    --env DB_URL=ecto://{{ postgres_admin_user }}:{{ postgres_admin_pass }}@postgres.{{ postgres_net }}/changelog
    --env CM_TOKEN={{ campaign_monitor_token }}
    gerhard/elixir:1.3.2-erl18.3.4.1
    ./script/prod

- name: compile static assets
  when: app_version | changed
  shell: >
    docker run --rm --tty
    --name dotcom.assets.{{ lookup('pipe','date +%Y%m%d.%H%M%S') }}
    --volume {{ web_volume_path }}/dotcom:/app:rw
    --workdir /app
    --log-driver syslog --log-opt tag=dotcom.{{ lookup('pipe','date +%Y%m%d.%H%M%S') }} --log-opt syslog-address={{ papertrail_log_destination }}
    --env MIX_ENV=prod
    node:6.3.0
    ./script/compile_static_assets

- name: configure HTTPS certificate
  notify: nginx restart
  copy:
    content: "{{ changelog_https_cert }}"
    dest: /etc/ssl/star.changelog.com.crt
    owner: root
    group: root
    mode: 0644

- name: configure HTTPS key
  notify: nginx restart
  copy:
    content: "{{ changelog_https_key }}"
    dest: /etc/ssl/star.changelog.com.key
    owner: root
    group: root
    mode: 0644

- name: configure HTTPS chain
  notify: restart nginx
  copy:
    content: "{{ changelog_https_chain }}"
    dest: /etc/ssl/star.changelog.com.fullchain.pem
    owner: root
    group: root
    mode: 0644

- name: create nginx site
  template:
    src: 2016.changelog.com.j2
    dest: "{{ nginx_config_dir }}/sites/{{ fqdn }}.site"

- name: reload nginx so that it resolves the new app host
  shell: >
    docker exec nginx.{{ nginx_net }} nginx -t &&
    docker kill -s HUP nginx.{{ nginx_net }}

- name: find all app instances older than the last one
  register: venerable_apps
  shell: >
    docker ps -q --filter label=fqdn={{ fqdn }} | tail -n +2

- name: cleanup app instances older than the last one
  ignore_errors: true
  shell: >
    docker stop {{ venerable_apps.stdout_lines | join(" ") }} ;
    docker rm -f {{ venerable_apps.stdout_lines | join(" ") }}

- name: reload nginx so that it removes all venerable app hosts
  shell: >
    docker exec nginx.{{ nginx_net }} nginx -t &&
    docker kill -s HUP nginx.{{ nginx_net }}
