- name: configure HTTPS certificate
  notify: nginx restart
  copy:
    content: "{{ lookup('env', 'HTTPS_CERT') }}"
    dest: /etc/ssl/star.changelog.com.crt
    owner: root
    group: root
    mode: 0644

- name: configure HTTPS key
  notify: nginx restart
  copy:
    content: "{{ lookup('env', 'HTTPS_KEY') }}"
    dest: /etc/ssl/star.changelog.com.key
    owner: root
    group: root
    mode: 0644

- name: configure HTTPS chain
  notify: nginx restart
  copy:
    content: "{{ lookup('env', 'HTTPS_CHAIN') }}"
    dest: /etc/ssl/star.changelog.com.fullchain.pem
    owner: root
    group: root
    mode: 0644

- name: create web volume
  file:
    dest: "{{ web_volume_path }}/{{ fqdn }}"
    state: directory
    recurse: yes

- name: create index.html
  template:
    src: index.html.j2
    dest: "{{ web_volume_path }}/{{ fqdn }}/index.html"

- name: create nginx site
  notify: reload nginx
  template:
    src: changelog.com.j2
    dest: "{{ nginx_config_dir }}/sites/{{ fqdn }}.site"
