resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: infrastructure
    type: git
    source:
      uri: git@github.com:thechangelog/infrastructure.git
      branch: master
      private_key: {{concourse_ssh_private_key}}

  - name: dotcom
    type: git
    source:
      uri: git@github.com:thechangelog/changelog.com.git
      branch: master
      private_key: {{concourse_ssh_private_key}}

  - name: daily
    type: time
    source:
      interval: 24h

  - name: slack
    type: slack-notification
    source:
      url: {{slack_webhook}}

jobs:
  - name: configure
    serial_groups:
      - backup
    plan:
      - do:
        - aggregate:
          - get: infrastructure
            trigger: true
          - get: daily
            trigger: true
        - task: default
          file: infrastructure/concourse/play.yml
          params:
            ANSIBLE_PLAYBOOK: default.yml
            CONCOURSE_SSH_PRIVATE_KEY: {{concourse_ssh_private_key}}
            SSH_KNOWN_HOSTS: {{ssh_known_hosts}}
            AUTHORIZED_KEYS: {{authorized_keys}}
            HTTPS_CERT: {{changelog_https_cert}}
            HTTPS_KEY: {{changelog_https_key}}
            HTTPS_CHAIN: {{changelog_https_chain}}
            DNSIMPLE_EMAIL: {{dnsimple_email}}
            DNSIMPLE_API_TOKEN: {{dnsimple_api_token}}
            PG_DOTCOM_PASS: {{postgres_admin_pass}}
            PG_CONCOURSE_PASS: {{postgres_concourse_pass}}
        - task: concourse
          file: infrastructure/concourse/play.yml
          params:
            ANSIBLE_PLAYBOOK: concourse.yml
            CONCOURSE_SSH_PRIVATE_KEY: {{concourse_ssh_private_key}}
            CONCOURSE_AUTH_PASS: {{concourse_auth_pass}}
            SSH_KNOWN_HOSTS: {{ssh_known_hosts}}
            PG_CONCOURSE_PASS: {{postgres_concourse_pass}}
        on_failure:
          put: slack
          params:
            text: <!here> hosts configuration failed https://ci.changelog.com/teams/main/pipelines/changelog.com
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
            username: concourse

  - name: backup
    serial_groups:
      - backup
    plan:
      - get: infrastructure
      - get: daily
        trigger: true
      - task: dotcom
        file: infrastructure/concourse/play.yml
        params:
          ANSIBLE_PLAYBOOK: dotcom.yml -t dotcom_backup -e dotcom_backup=true
          CONCOURSE_SSH_PRIVATE_KEY: {{concourse_ssh_private_key}}
          SSH_KNOWN_HOSTS: {{ssh_known_hosts}}
          DOTCOM_BACKUP_AWS_REGION: {{dotcom_backup_aws_region}}
          DOTCOM_BACKUP_S3_BUCKET: {{dotcom_backup_s3_bucket}}
          DOTCOM_BACKUP_AWS_ACCESS_KEY_ID: {{dotcom_backup_aws_access_key_id}}
          DOTCOM_BACKUP_AWS_SECRET_ACCESS_KEY: {{dotcom_backup_aws_secret_access_key}}
          PG_DOTCOM_PASS: {{postgres_admin_pass}}

  - name: deploy
    serial_groups:
      - backup
    plan:
      - do:
        - aggregate:
          - get: infrastructure
            trigger: true
          - get: dotcom
            trigger: true
          - get: daily
            trigger: true
        - task: deploy dotcom
          file: infrastructure/concourse/play.yml
          params:
            ANSIBLE_PLAYBOOK: dotcom.yml
            CONCOURSE_SSH_PRIVATE_KEY: {{concourse_ssh_private_key}}
            SSH_KNOWN_HOSTS: {{ssh_known_hosts}}
            DOTCOM_BACKUP_AWS_REGION: {{dotcom_backup_aws_region}}
            DOTCOM_BACKUP_S3_BUCKET: {{dotcom_backup_s3_bucket}}
            DOTCOM_BACKUP_AWS_ACCESS_KEY_ID: {{dotcom_backup_aws_access_key_id}}
            DOTCOM_BACKUP_AWS_SECRET_ACCESS_KEY: {{dotcom_backup_aws_secret_access_key}}
            PG_DOTCOM_PASS: {{postgres_admin_pass}}
            CM_SMTP_TOKEN: {{campaign_monitor_smtp_token}}
            CM_API_TOKEN: {{campaign_monitor_api_token}}
            AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
            AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
            SECRET_KEY_BASE: {{secret_key_base}}
            SIGNING_SALT: {{signing_salt}}
        on_success:
            put: slack
            params:
              text: "production deploy success! :rocket:"
              icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
              username: concourse
        on_failure:
            put: slack
            params:
              text: "production deploy failed :scream: https://ci.changelog.com/teams/main/pipelines/changelog.com"
              icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
              username: concourse
