- name: docker info
  register: docker_info
  shell: >
    docker info

- name: debug docker_info
  when: debug | default(false)
  debug:
    var: docker_info

- name: ensure docker uses devicemapper with thinpool
  assert:
    that:
      - "'Storage Driver: devicemapper' in docker_info.stdout"
      - "'Pool Name: docker-thinpool' in docker_info.stdout"
      - "'Deferred Removal Enabled: true' in docker_info.stdout"
