- name: configure container logs rotation
  copy:
    src: docker.logrotate
    dest: /etc/logrotate.d/docker

- name: read container logs rotation config
  register: container_logs_rotation
  command: logrotate --debug --verbose /etc/logrotate.d/docker

- name: debug container logs rotation config
  when: debug | default(false)
  debug:
    var: container_logs_rotation

- name: check container logs rotation
  assert:
    that:
      - "'/var/lib/docker/containers/*/*.log  after 1 days (7 rotations)' in container_logs_rotation.stderr"

