- name: ensure Docker network exists
  shell: >
    docker network inspect {{ postgres_net }} ||
    docker network create {{ postgres_net }}

- name: create volume path
  file:
    dest: "{{ postgres_volume_path }}"
    state: directory
    recurse: yes

- name: ensure container image exists
  shell: >
    docker pull postgres:{{ postgres_version }}

- name: ensure container is running
  docker:
    name: "postgres.{{ postgres_net }}"
    image: "postgres:{{ postgres_version }}"
    pull: missing
    state: reloaded
    restart_policy: always
    net: "{{ postgres_net }}"
    env:
      POSTGRES_USER: "{{ postgres_admin_user }}"
      POSTGRES_PASSWORD: "{{ postgres_admin_pass }}"
    volumes:
      - "{{ postgres_volume_path }}:/var/lib/postgresql/data:rw"
    ports:
      - "127.0.0.1:{{ postgres_port }}:5432"
    log_driver: syslog
    log_opt:
      syslog-address: "{{ papertrail_log_destination }}"
      tag: "postgres.{{ postgres_net }}"
