- name: check if physical volume created
  register: pv
  ignore_errors: true
  command: "pvdisplay {{ lvm_pvdev }}"

- name: create physical volume
  when: pv | failed
  command: "pvcreate {{ lvm_pvdev }}"

- name: ensure volume group exists
  lvg:
    vg: "{{ lvm_vg }}"
    pvs: "{{ lvm_pvdev }}"
    pesize: "{{ lvm_vgsize }}"
    state: present
